services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: talkeret/vprofiledb
    container_name: vprodb

    ports:
      - "${DB_PORT}:3306"

    volumes:
      - vprodbdata:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  vprocache01:
    image: memcached
    container_name: vprocache01

    ports:
      - "${MEMCACHED_PORT}:11211"

  vpromq01:
    image: rabbitmq
    container_name: vpromq01

    ports:
      - "5672:5672"

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  vproapp:
    build:
      context: .
      dockerfile: ./Docker-files/app/Dockerfile
    image: talkeret/vprofileapp
    container_name: vproapp

    env_file:
      - .env

    depends_on:
      vprodb:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully

    ports:
      - "${APP_PORT}:8080"

    volumes:
      - vproappdata:/usr/local/tomcat/webapps

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  vproweb:
    build:
      context: ./Docker-files/web
    image: talkeret/vprofileweb
    container_name: vproweb

    ports:
      - "${WEB_PORT}:80"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

    depends_on:
      - vproapp

  flyway:
    image: flyway/flyway:10
    command: -connectRetries=60 migrate
    volumes:
      - ./sql:/flyway/sql

    environment:
      FLYWAY_URL: jdbc:mysql://${DB_HOST:-vprodb}:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false
      FLYWAY_USER: root
      FLYWAY_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    depends_on:
      vprodb:
        condition: service_healthy

volumes:
  vprodbdata: {}
  vproappdata: {}
