# =======================
# DATABASE
# =======================

jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://${DB_HOST_NAME}:${DB_HOST_PORT:3306}/${DB_NAME}?useUnicode=true&characterEncoding=UTF-8
jdbc.username=${DB_USER}
jdbc.password=${DB_PASS}

# =======================
# MEMCACHED
# =======================

# Active Host
memcached.active.host=${MEMCACHED_HOST_NAME}
memcached.active.port=${MEMCACHED_HOST_PORT:11211}

# Standby Host
memcached.standBy.host=${MEMCACHED_STANDBY_HOST:127.0.0.2}
memcached.standBy.port=${MEMCACHED_STANDBY_PORT:11211}

# =======================
# RABBITMQ
# =======================

rabbitmq.address=${RABBITMQ_HOST_NAME}
rabbitmq.port=${RABBITMQ_HOST_PORT:5672}
rabbitmq.username=${RABBITMQ_USER}
rabbitmq.password=${RABBITMQ_PASS}

# AWS / Docker Selection
spring.rabbitmq.ssl.enabled=${RABBITMQ_SSL:false}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:/}

# =======================
# ELASTICSEARCH
# =======================

elasticsearch.host=${ELASTICSEARCH_HOST_NAME:elasticsearch}
elasticsearch.port=${ELASTICSEARCH_HOST_PORT:9200}
elasticsearch.scheme=${ELASTICSEARCH_SCHEME:https}
elasticsearch.cluster=vprofile
elasticsearch.node=vprofilenode

# =======================
# SPRING SECURITY
# =======================

spring.security.user.name=${SPRING_USER}
spring.security.user.password=${SPRING_PASS}
spring.security.user.roles=ADMIN

# =======================
# FILE UPLOAD
# =======================

spring.servlet.multipart.max-file-size=128KB
spring.servlet.multipart.max-request-size=128KB

# =======================
# SPRING MVC
# =======================

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# =======================
# LOGGING
# =======================

logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type=OFF

# Debug Logging for SecurityServiceImpl
logging.level.com.visualpathit.account.service.SecurityServiceImpl=OFF

# =======================
# JPA
# =======================

# Hibernate SQL Queries
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false