pipeline {

    agent any

    tools {
        maven 'Maven 3.9.15'
    }

    environment {
        // AWS Variables:
        AWS_REGION = "us-east-1"

        // ECR Variables:
        ECR_REGISTRY = "943560362977.dkr.ecr.us-east-1.amazonaws.com"
        ECR_REPO = "vprofile/app"
        IMAGE_TAG = "${BUILD_NUMBER}"

        // ECS Variables:
        PRIVATE_SUBNETS = "subnet-0e50e624c69122c0b,subnet-0fa32fc914f95d698"
        ECS_SECURITY_GROUP = "sg-0604b1974cacd54c1"
    }

    stages {

        stage('Clone') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/talkeret1/vprofile-ci-cd.git'
            }
        }

        stage('Code Quality') {
            steps {
                sh 'mvn validate checkstyle:checkstyle'
            }
        }

        stage('Build WAR') {
            steps {
                sh 'mvn clean verify'
            }
        }

        stage('SonarQube Analysis') {
            environment {
                scannerHome = tool 'SonarScanner'
            }
            steps {
                withSonarQubeEnv('sonarqube') {
                    sh '''
                    $scannerHome/bin/sonar-scanner \
                    -Dsonar.projectKey=vprofile \
                    -Dsonar.sources=src/main/java \
                    -Dsonar.tests=src/test/java \
                    -Dsonar.java.binaries=target/classes \
                    -Dsonar.java.test.binaries=target/test-classes \
                    -Dsonar.junit.reportPaths=target/surefire-reports \
                    -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
                    -Dsonar.sourceEncoding=UTF-8 \
                    -Dsonar.java.source=17 \
                    -Dsonar.java.target=17
                    '''
                }
            }
        }

        stage('Quality Gate') {
            steps {
                waitForQualityGate abortPipeline: true
            }
        }

        stage('Docker Build') {
            steps {
                sh """
                docker build \
                -t $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG \
                -t $ECR_REGISTRY/$ECR_REPO:latest \
                -f Docker-files/app/Dockerfile .
                """
            }
        }

        stage('Trivy Scan') {
            steps {
                sh """
                trivy image --severity HIGH,CRITICAL \
                $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
                """
            }
        }

        stage('ECR Login') {
            steps {
                withCredentials([aws(credentialsId: 'aws-credentials')]) {
                    sh """
                    aws ecr get-login-password --region $AWS_REGION | \
                    docker login --username AWS --password-stdin $ECR_REGISTRY
                    """
                }
            }
        }

        stage('Docker Push to ECR') {
            steps {
                sh """
                docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
                docker push $ECR_REGISTRY/$ECR_REPO:latest
                """
            }
        }

        stage('Check ECS Status') {
            steps {
                withCredentials([aws(credentialsId: 'aws-credentials')]) {
                    script {
                        def serviceCount = sh(
                            script: """
                            aws ecs describe-services \
                            --cluster vprofile-cluster \
                            --services vproapp-service \
                            --query "length(services)" \
                            --output text \
                            --region $AWS_REGION
                            """,
                            returnStdout: true
                        ).trim()
                        echo "ECS service status: ${serviceCount == '1' ? 'EXISTS' : 'MISSING'}"
                        env.ECS_EXISTS = (serviceCount == "1") ? "true" : "false"
                        echo "ECS_EXISTS = ${env.ECS_EXISTS}"
                    }
                }
            }
        }

        stage('Deploy ECS Service') {
            when {
                expression {
                    env.ECS_EXISTS == "true"
                }
            }

            steps {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-credentials']
                ]) {
                    echo "ECS service exists. Triggering new deployment..."
                    sh """
                    aws ecs update-service \
                    --cluster vprofile-cluster \
                    --service vproapp-service \
                    --force-new-deployment \
                    --region $AWS_REGION
                    """
                }
            }
        }
    }

    post {
        always {
            sh 'docker system prune -f'
            echo 'Docker system cleaned up.'
        }
    }
}