pipeline {
    agent any
    
    tools {
       maven 'Maven 3.9.15'
    }

    environment {
        IMAGE_NAME = "talkeret/vprofileapp"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Clone') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/talkeret1/vprofile-ci-cd.git'
            }
        }

        stage('Code Quality') {
            steps {
                sh 'mvn validate checkstyle:checkstyle'
            }
        }
        
        stage('Build WAR') {
            steps {
                sh 'mvn clean verify'
            }
   
        }

        stage('SonarQube Analysis') {
            environment {
                scannerHome = tool 'SonarScanner'
            }
            steps {
                withSonarQubeEnv('sonarqube') {
                    sh '''
                    $scannerHome/bin/sonar-scanner \
                    -Dsonar.projectKey=vprofile \
                    -Dsonar.sources=src \
                    -Dsonar.java.binaries=target/classes
                    '''
                }
            }
        }
        
        stage('Quality Gate') {
            steps {
                waitForQualityGate abortPipeline: true
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest -f Docker-files/app/Dockerfile .'
            }
        }

        stage('Trivy Scan') {
            steps {
                // sh 'trivy image --severity HIGH,CRITICAL --exit-code 1 $IMAGE_NAME:$IMAGE_TAG'
                sh 'trivy image --severity HIGH,CRITICAL $IMAGE_NAME:$IMAGE_TAG'
            }
        }

        stage('Docker Push') {

            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-token', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_TOKEN')]) {
                    sh '''
                    echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
                    docker push $IMAGE_NAME:$IMAGE_TAG
                    docker push $IMAGE_NAME:latest
                    '''
                }
            }
        }
    }
}